package main

var KEYMAP = map[string]string{
	// JP {{{
	"JP_ZHTG":  "半/全",
	"JP_YEN":   "\\ / |",
	"JP_CIRC":  "^ / ~",
	"JP_AT":    "@ / `",
	"JP_LBRC":  "[ / {",
	"JP_COLN":  ": / *",
	"JP_RBRC":  "] / }",
	"JP_BSLS":  "\\ / _",
	"JP_MHEN":  "無変換",
	"JP_HENK":  "変換",
	"JP_KANA":  "カひロ",
	"JP_MKANA": "かな",
	"JP_MEISU": "英数",
	"JP_DQT":   "\"",
	"JP_AMPR":  "&",
	"JP_QUOT":  "'",
	"JP_LPRN":  "(",
	"JP_RPRN":  ")",
	"JP_EQL":   ":",
	"JP_TILD":  "~",
	"JP_PIPE":  "|",
	"JP_GRV":   "`",
	"JP_LCBR":  "{",
	"JP_PLUS":  "+",
	"JP_ASTR":  "*",
	"JP_RCBR":  "}",
	"JP_UNDS":  "_",
	"JP_MINS":  "-",
	"JP_SCLN":  ";",
	"JP_COMM":  ",",
	"JP_DOT":   ".",
	"JP_SLSH":  "/",
	"JP_EXLM":  "!",
	"JP_HASH":  "#",
	"JP_DLR":   "$",
	"JP_PERC":  "%",
	"JP_LT":    "<",
	"JP_GT":    ">",
	"JP_QUES":  "?",
	// }}}

	// 普通 {{{

	"KC_A":          "a",
	"KC_B":          "b",
	"KC_C":          "c",
	"KC_D":          "d",
	"KC_E":          "e",
	"KC_F":          "f",
	"KC_G":          "g",
	"KC_H":          "h",
	"KC_I":          "i",
	"KC_J":          "j",
	"KC_K":          "k",
	"KC_L":          "l",
	"KC_M":          "m",
	"KC_N":          "n",
	"KC_O":          "o",
	"KC_P":          "p",
	"KC_Q":          "q",
	"KC_R":          "r",
	"KC_S":          "s",
	"KC_T":          "t",
	"KC_U":          "u",
	"KC_V":          "v",
	"KC_W":          "w",
	"KC_X":          "x",
	"KC_Y":          "y",
	"KC_Z":          "z",
	"KC_1":          "1",
	"KC_2":          "2",
	"KC_3":          "3",
	"KC_4":          "4",
	"KC_5":          "5",
	"KC_6":          "6",
	"KC_7":          "7",
	"KC_8":          "8",
	"KC_9":          "9",
	"KC_0":          "0",
	"KC_ENTER":      "Enter",
	"KC_ESCAPE":     "Esc",
	"KC_BSPACE":     "Bs",
	"KC_TAB":        "Tab",
	"KC_SPACE":      "Space",
	"KC_MINUS":      "- _",
	"KC_EQUAL":      "= +",
	"KC_LBRACKET":   "[ {",
	"KC_RBRACKET":   "] }",
	"KC_BSLASH":     "\\ |",
	"KC_NONUS_HASH": "# ~",
	"KC_SCOLON":     "; :",
	"KC_QUOTE":      "' \"",
	"KC_GRAVE":      "` ~ (半全)",
	"KC_COMMA":      ", <",
	"KC_DOT":        ". >",
	"KC_SLASH":      "/ ?",
	"KC_CAPSLOCK":   "CaLck",
	"KC_F1":         "F1",
	"KC_F2":         "F2",
	"KC_F3":         "F3",
	"KC_F4":         "F4",
	"KC_F5":         "F5",
	"KC_F6":         "F6",
	"KC_F7":         "F7",
	"KC_F8":         "F8",
	"KC_F9":         "F9",
	"KC_F10":        "F10",
	"KC_F11":        "F11",
	"KC_F12":        "F12",
	"KC_F13":        "F13",
	"KC_F14":        "F14",
	"KC_F15":        "F15",
	"KC_F16":        "F16",
	"KC_F17":        "F17",
	"KC_F18":        "F18",
	"KC_F19":        "F19",
	"KC_F20":        "F20",
	"KC_F21":        "F21",
	"KC_F22":        "F22",
	"KC_F23":        "F23",
	"KC_F24":        "F24",
	// }}}

	// ten key {{{
	"KC_NUMLOCK":     "NL", // "Keypad Num Lock / Clear",
	"KC_KP_SLASH":    "Keypad /",
	"KC_KP_ASTERISK": "Keypad *",
	"KC_KP_MINUS":    "Keypad -",
	"KC_KP_PLUS":     "Keypad +",
	"KC_KP_ENTER":    "Keypad Enter",
	"KC_KP_1":        "Keypad 1 / End",
	"KC_KP_2":        "Keypad 2 / Down Arrow",
	"KC_KP_3":        "Keypad 3 / Page Down",
	"KC_KP_4":        "Keypad 4 / Left Arrow",
	"KC_KP_5":        "Keypad 5 ",
	"KC_KP_6":        "Keypad 6 / Right Arrow",
	"KC_KP_7":        "Keypad 7 / Home",
	"KC_KP_8":        "Keypad 8 / Up Arrow",
	"KC_KP_9":        "Keypad 9 / Page Up",
	"KC_KP_0":        "Keypad 0 / Insert",
	"KC_KP_DOT":      "Keypad . / Delete",
	"KC_KP_EQUAL":    "Keypad =",
	"KC_NLCK":        "Keypad Num Lock / Clear",
	"KC_PSLS":        "Keypad /",
	"KC_PAST":        "Keypad *",
	"KC_PMNS":        "Keypad -",
	"KC_PPLS":        "Keypad +",
	"KC_PENT":        "Keypad Enter",
	"KC_P1":          "Keypad 1 and End",
	"KC_P2":          "Keypad 2 and Down Arrow",
	"KC_P3":          "Keypad 3 and Page Down",
	"KC_P4":          "Keypad 4 and Left Arrow",
	"KC_P5":          "Keypad 5",
	"KC_P6":          "Keypad 6 and Right Arrow",
	"KC_P7":          "Keypad 7 and Home",
	"KC_P8":          "Keypad 8 and Up Arrow",
	"KC_P9":          "Keypad 9 and Page Up",
	"KC_P0":          "Keypad 0 and Insert",
	"KC_PDOT":        "Keypad . and Delete",
	"KC_PEQL":        "Keypad =",
	// }}}

	// nazo {{{

	"KC_PSCREEN":      "PS",        //  "Print Screen",
	"KC_SCROLLLOCK":   "SL(BD)",    //Scroll Lock, (Brightness Down)",
	"KC_PAUSE":        "Pause(BU)", // "Pause, (Brightness Up)",
	"KC_INSERT":       "Ins",
	"KC_HOME":         "Home",
	"KC_PGUP":         "PU",     // "Page Up",
	"KC_DELETE":       "Delete", // "Forward Delete",
	"KC_END":          "End",
	"KC_PGDOWN":       "PD",     //Page Down",
	"KC_RIGHT":        "Right",  // Right Arrow",
	"KC_LEFT":         "Left",   // Left Arrow",
	"KC_DOWN":         "Down",   // Down Arrow",
	"KC_UP":           "Up",     // Up Arrow",
	"KC_NONUS_BSLASH": "\\ / |", // "Non-US \\ / |",
	"KC_APPLICATION":  "Win",    // Application (Windows Menu Key)",
	"KC_POWER":        "Power",  // "Power (macOS)",

	"KC_EXEC": "Execute",
	"KC_SLCT": "Select",
	"KC_AGIN": "Again",
	"KC_PSTE": "Paste",

	"KC_EXECUTE":        "Execute",
	"KC_HELP":           "Help",
	"KC_MENU":           "Menu",
	"KC_SELECT":         "Select",
	"KC_STOP":           "Stop",
	"KC_AGAIN":          "Again",
	"KC_UNDO":           "Undo",
	"KC_CUT":            "Cut",
	"KC_COPY":           "Copy",
	"KC_PASTE":          "Paste",
	"KC_FIND":           "Find",
	"KC__MUTE":          "Mute", // "Mute (macOS)",
	"KC__VOLUP":         "VU",   // "Volume Up (macOS)",
	"KC__VOLDOWN":       "VD",   // "Volume Down (macOS)",
	"KC_LOCKING_CAPS":   "CL",   // "Caps Lock",
	"KC_LOCKING_NUM":    "NL",   // "Num Lock",
	"KC_LOCKING_SCROLL": "SL",   // "Scroll Lock",
	"KC_KP_COMMA":       "Keypad ,",
	"KC_KP_EQUAL_AS400": "Keypad = on AS/400 keyboards",
	"KC_INT1":           "J \\ / _",   // "JIS \\ / _",
	"KC_INT2":           "J カひ",       // "JIS Katakana/Hiragana",
	"KC_INT3":           "J \\ / |",   // "JIS \\ / |",
	"KC_INT4":           "J Henkan",   // "JIS Henkan",
	"KC_INT5":           "J Muhenkan", // "JIS Muhenkan",
	"KC_INT6":           "J Numpad ,", // "JIS Numpad ,",
	"KC_INT7":           "International 7",
	"KC_INT8":           "International 8",
	"KC_INT9":           "International 9",

	"KC_ALT_ERASE":          "Alternate Erase",
	"KC_SYSREQ":             "SysReq/Attention",
	"KC_CANCEL":             "Cancel",
	"KC_CLEAR":              "Clear",
	"KC_PRIOR":              "Prior",
	"KC_RETURN":             "Return",
	"KC_SEPARATOR":          "Separator",
	"KC_OUT":                "Out",
	"KC_OPER":               "Oper",
	"KC_CLEAR_AGAIN":        "Clear/Again",
	"KC_CRSEL":              "CrSel/Props",
	"KC_EXSEL":              "ExSel",
	"KC_SYSTEM_POWER":       "Power", // "System Power Down",
	"KC_SYSTEM_SLEEP":       "Sleep", // "System Sleep",
	"KC_SYSTEM_WAKE":        "Wake",  // "System Wake",
	"KC_AUDIO_MUTE":         "Mute",
	"KC_AUDIO_VOL_UP":       "VU", // "Volume Up",
	"KC_AUDIO_VOL_DOWN":     "VD", // "Volume Down",
	"KC_MEDIA_NEXT_TRACK":   "Next Track",
	"KC_MEDIA_PREV_TRACK":   "Previous Track",
	"KC_MEDIA_STOP":         "Stop Track (Windows)",
	"KC_MEDIA_PLAY_PAUSE":   "Play/Pause Track",
	"KC_MEDIA_SELECT":       "Launch Media Player (Windows)",
	"KC_MEDIA_EJECT":        "Eject (macOS)",
	"KC_MAIL":               "Launch Mail (Windows)",
	"KC_CALCULATOR":         "Launch Calculator (Windows)",
	"KC_MY_COMPUTER":        "Launch My Computer (Windows)",
	"KC_WWW_SEARCH":         "Browser Search (Windows)",
	"KC_WWW_HOME":           "Browser Home (Windows)",
	"KC_WWW_BACK":           "Browser Back (Windows)",
	"KC_WWW_FORWARD":        "Browser Forward (Windows)",
	"KC_WWW_STOP":           "Browser Stop (Windows)",
	"KC_WWW_REFRESH":        "Browser Refresh (Windows)",
	"KC_WWW_FAVORITES":      "Browser Favorites (Windows)",
	"KC_MEDIA_FAST_FORWARD": "Next Track (macOS)",
	"KC_MEDIA_REWIND":       "Previous Track (macOS)",
	"KC_BRIGHTNESS_UP":      "BU", // "Brightness Up",
	"KC_BRIGHTNESS_DOWN":    "BD", // "Brightness Down",

	"KC_LANG1": "kana ", // Hangul/English",
	"KC_LANG2": "eisu",  // Hanja",
	"KC_LANG3": "JIS Katakana",
	"KC_LANG4": "JIS Hiragana",
	"KC_LANG5": "JIS Zenkaku/Hankaku",
	"KC_LANG6": "Language 6",
	"KC_LANG7": "Language 7",
	"KC_LANG8": "Language 8",
	"KC_LANG9": "Language 9",

	"KC_HAEN": "Hangul/English",
	"KC_HANJ": "Hanja",
	"KC_ERAS": "Alternate Erase",
	"KC_CLR":  "Clear",

	"KC_MNXT": "Next Track",
	"KC_MPRV": "Previous Track",
	"KC_MSTP": "Stop Track (Windows)",
	"KC_MPLY": "Play/Pause Track",
	"KC_MSEL": "Launch Media Player (Windows)",
	"KC_EJCT": "Eject (macOS)",
	"KC_CALC": "Launch Calculator (Windows)",
	"KC_MYCM": "Launch My Computer (Windows)",
	"KC_WSCH": "Browser Search (Windows)",
	"KC_WHOM": "Browser Home (Windows)",
	"KC_WBAK": "Browser Back (Windows)",
	"KC_WFWD": "Browser Forward (Windows)",
	"KC_WSTP": "Browser Stop (Windows)",
	"KC_WREF": "Browser Refresh (Windows)",
	"KC_WFAV": "Browser Favorites (Windows)",
	// }}}

	"KC_LCTRL":  "Ctrl",   // "Left Control",
	"KC_LSHIFT": "Shift",  // "Left Shift",
	"KC_LALT":   "Alt",    // "Left Alt",
	"KC_LGUI":   "GUI",    // "Left GUI (Windows/Command/Meta key)",
	"KC_RCTRL":  "RCtrl",  // "Right Control",
	"KC_RSHIFT": "RShift", // "Right Shift",
	"KC_RALT":   "RAlt",   // "Right Alt (AltGr)",
	"KC_RGUI":   "RGUI",   // "Right GUI (Windows/Command/Meta key)",

	"KC_ENT":  "Ent", // "Return (Enter)",
	"KC_ESC":  "Esc", // "Escape",
	"KC_BSPC": "Bs",  // "Delete (Backspace)",
	"KC_SPC":  "Spc", // "Spacebar",
	"KC_MINS": "- / _",
	"KC_EQL":  "= / +",
	"KC_LBRC": "[ / {",
	"KC_RBRC": "] / }",
	"KC_BSLS": "\\ / |",
	"KC_NUHS": "# / ~", // "Non-US # / ~",
	"KC_SCLN": "; / :",
	"KC_QUOT": "' / \"",
	"KC_GRV":  "` / ~",
	"KC_ZKHK": "J 全/半",
	"KC_COMM": ", / <",
	"KC_SLSH": "/ / ?",
	"KC_CLCK": "CL",
	"KC_CAPS": "CL",
	"KC_PSCR": "PS",
	"KC_SLCK": "SL",
	"KC_BRMD": "BD",    // "Brightness Down (macOS)",
	"KC_PAUS": "P, BU", // "Pause, Brightness Up (macOS)",
	"KC_BRK":  "P, BU", // "Pause, Brightness Up (macOS)",
	"KC_BRMU": "P, BU", // "Pause, Brightness Up (macOS)",
	"KC_INS":  "Ins",
	"KC_DEL":  "Del",
	"KC_PGDN": "PD",
	"KC_RGHT": "Right",
	"KC_NUBS": "N \\ / |",
	"KC_APP":  "APP", // "Application (Windows Menu Key)",
	"KC_LCAP": "CL",
	"KC_LNUM": "NL",
	"KC_LSCR": "SL",
	"KC_PCMM": "Keypad ,",
	"KC_RO":   "J \\ / _",
	"KC_KANA": "J カ/ひ",
	"KC_JYEN": "J \\ / |",
	"KC_HENK": "J Henkan",
	"KC_MHEN": "J Muhenkan",

	"KC_LCTL": "Ctrl",
	"KC_LSFT": "Shift",
	"KC_LCMD": "GUI", // (Windows/Command/Meta key)",
	"KC_LWIN": "GUI", // (Windows/Command/Meta key)",
	"KC_RCTL": "RCtrl",
	"KC_RSFT": "RShift",
	"KC_ALGR": "RAlt", //  (AltGr)",
	"KC_RCMD": "RGUI", //  (Windows/Command/Meta key)",
	"KC_RWIN": "RGUI", //  (Windows/Command/Meta key)",
	"KC_PWR":  "Power",
	"KC_SLEP": "Sleep",
	"KC_WAKE": "Wake",
	"KC_MUTE": "Mute",
	"KC_VOLU": "VU",
	"KC_VOLD": "VD",
	"KC_MFFD": "N Track",
	"KC_MRWD": "P Track",
	"KC_BRIU": "Bri Up",
	"KC_BRID": "Bri Down",
	"KC_NO":   "---",
}
